server:
  port: 80
spring:
  application:
    name: api-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.200.128:8848
    gateway:
      discovery:      #是否与服务发现组件进行结合，通过 serviceId(必须设置成大写) 转发到具体的服务实例。默认为false，设为true便开启通过服务中心的自动根据 serviceId 创建路由的功能。
        locator:      #路由访问方式：http://Gateway_HOST:Gateway_PORT/大写的serviceId/**，其中微服务应用名默认大写访问。
          enabled: true
      routes:
        - id: service-product
          uri: lb://service-product   #负载均衡
          predicates:
            - Path=/*/product/** # 路径匹配
        - id: service-item1
          uri: lb://service-item1   #负载均衡
          predicates:
            - Path=/*/item/** # 路径匹配

        #==================web前端==========================
        - id: web-item # 商品详情
          uri: lb://web-all
          predicates:
            - Host=item.gmall.com #通过域名访问
        - id: web-index # 首页
          uri: lb://web-all
          predicates:
            - Host=www.gmall.com #通过域名访问
        - id: web-list
          uri: lb://web-all
          predicates:
            - Host=list.gmall.com
