server:
  port: 8206

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*Mapper.xml
  #编写复杂的sql语句，mybatis-plus对多表关联支持性查，所以需要手写

spring:
  cloud:
    sentinel:
      transport:
        dashboard: http://192.168.200.128:8858   #熔断降级

  rabbitmq:
    host: 192.168.200.128
    port: 5672
    username: admin
    password: admin
  redis:                        #配置缓存
    host: 192.168.200.128
    port: 6379
    database: 0
    timeout: 1800000
    password:
    lettuce:
      pool:
        max-active: 20 #最大连接数
        max-wait: -1    #最大阻塞等待时间(负数表示没限制)
        max-idle: 5    #最大空闲
        min-idle: 0     #最小空闲
  datasource:
    type: com.zaxxer.hikari.HikariDataSource  #springboot 2.x 都使用这个连接池   号称世界最快的连接池
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.200.128:3306/gmall_product?characterEncoding=utf-8&useSSL=false
    username: root
    password: root
    hikari:
      connection-test-query: SELECT 1
      connection-timeout: 60000
      idle-timeout: 500000
      max-lifetime: 540000
      maximum-pool-size: 12
      minimum-idle: 10
      pool-name: SPHHikariPool
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
fileServer:   #后期会把文件图片上传 ，url是上传地址    fastDFS 分布式文件系统的ip:port
  url: http://192.168.200.128:8080/